#!/usr/bin/env node
'use strict';

/**
 * Web-scraping script generated by WebScraper.
 *
 * Setup:  npm i puppeteer-extra puppeteer-extra-plugin-stealth puppeteer
 * Run:    node workflow.js
 */

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());

const STEALTH_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

async function applyStealthToPage(page) {
  try {
    const client = await page.target().createCDPSession();
    await client.send('Emulation.setUserAgentOverride', {
      userAgent: STEALTH_UA,
      platform: 'Win32',
    });
    await client.send('Emulation.setLocaleOverride', { locale: 'en-US' }).catch(() => {});
    await client.send('Emulation.setTimezoneOverride', { timezoneId: 'America/New_York' }).catch(() => {});
    await page.evaluateOnNewDocument(() => {
      Object.defineProperty(navigator, 'webdriver', { get: () => false, configurable: true });
    });
  } catch (_) {}
}

/**
 * Try each selector in order; return the first ElementHandle that resolves.
 * selectors = [{ value: string, type: 'css'|'xpath' }, ...]
 */
async function resolveElement(page, selectors) {
  for (const { value, type } of selectors) {
    try {
      const selector =
        type === 'xpath'
          ? `::-p-xpath(${value})`
          : value;
      const el = await page.$(selector);
      if (el) return el;
    } catch (_) {}
  }
  return null;
}

/**
 * Same as resolveElement but returns ALL matching handles for the first
 * selector that yields at least one result.
 */
async function resolveElements(page, selectors) {
  for (const { value, type } of selectors) {
    try {
      const selector =
        type === 'xpath'
          ? `::-p-xpath(${value})`
          : value;

      const els = await page.$$(selector);
      if (els && els.length > 0) return els;
    } catch (_) {}
  }
  return [];
}

/**
 * Wait until any selector in the list appears within timeout ms.
 * Returns the ElementHandle of the first match found.
 * Throws if nothing resolves in time.
 */
async function waitForAny(page, selectors, timeout = 10000) {
  const deadline = Date.now() + timeout;
  let lastErr;
  while (Date.now() < deadline) {
    for (const { value, type } of selectors) {
      try {
        const el = type === 'xpath'
          ? (await page.$x(value))[0]
          : await page.$(value);
        if (el) return el;
      } catch (e) { lastErr = e; }
    }
    await new Promise(r => setTimeout(r, 200));
  }
  const tried = selectors.map(s => `[${s.type}] ${s.value}`).join(', ');
  throw new Error(`waitForAny: none matched within ${timeout}ms. Tried: ${tried}`);
}

/**
 * Run page.evaluate(fn, el) with XPath-aware element resolution.
 */
async function evalOnElement(page, selectors, fn) {
  const el = await resolveElement(page, selectors);
  if (!el) throw new Error('evalOnElement: element not found for selectors: ' + JSON.stringify(selectors));
  return page.evaluate(fn, el);
}

/**
 * Run page.evaluate(fn, el) on ALL elements matched by the first working selector.
 */
async function evalOnElements(page, selectors, fn) {
  const els = await resolveElements(page, selectors);
  if (!els.length) return [];
  return Promise.all(els.map(el => page.evaluate(fn, el)));
}

// ─── Field transform runtime (clean / split per-field pipelines) ──────────
function __ftCleanValue(value, ops) {
  if (!Array.isArray(ops) || ops.length === 0) return value;
  let v = value;
  for (const op of ops) {
    if (!op || typeof op !== 'object') continue;
    const s = v == null ? '' : String(v);
    switch (op.op) {
      case 'trim':        v = s.trim(); break;
      case 'collapse_ws': v = s.replace(/\s+/g, ' ').trim(); break;
      case 'lowercase':   v = s.toLowerCase(); break;
      case 'uppercase':   v = s.toUpperCase(); break;
      case 'capitalize':  v = s ? s.charAt(0).toUpperCase() + s.slice(1) : s; break;
      case 'replace':
        if (op.all === false) {
          v = s.replace(op.find != null ? String(op.find) : '', op.with != null ? String(op.with) : '');
        } else {
          v = s.split(op.find != null ? String(op.find) : '').join(op.with != null ? String(op.with) : '');
        }
        break;
      case 'regex_replace':
        try { v = s.replace(new RegExp(op.pattern || '', op.flags != null ? op.flags : 'g'), op.with != null ? String(op.with) : ''); }
        catch (_e) { v = s; }
        break;
      case 'remove':
        try { v = s.replace(new RegExp(op.pattern || '', op.flags != null ? op.flags : 'g'), ''); }
        catch (_e) { v = s; }
        break;
      case 'regex_extract':
        try {
          const m = s.match(new RegExp(op.pattern || '', op.flags || ''));
          if (!m) { v = null; }
          else { const g = op.group != null ? op.group : 0; v = m[g] != null ? m[g] : null; }
        } catch (_e) { v = null; }
        break;
      case 'extract_number': {
        const m = s.replace(/(\d),(?=\d{3}\b)/g, '$1').match(/-?\d+(?:\.\d+)?/);
        v = m ? m[0] : null;
        break;
      }
      case 'to_number': {
        const n = Number(s.replace(/[^0-9.\-eE+]/g, ''));
        v = Number.isNaN(n) ? null : n;
        break;
      }
      case 'prepend': v = (op.text != null ? String(op.text) : '') + s; break;
      case 'append':  v = s + (op.text != null ? String(op.text) : ''); break;
      case 'slice':   v = s.slice(op.start != null ? Number(op.start) : 0, op.end != null && op.end !== '' ? Number(op.end) : undefined); break;
      case 'strip_html': v = s.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim(); break;
      case 'default': v = (v == null || s === '') ? (op.value != null ? op.value : '') : v; break;
      case 'custom':
        try { v = (new Function('value', 'return (' + (op.expr || 'value') + ');'))(v); }
        catch (_e) { /* leave value unchanged on error */ }
        break;
      default: break;
    }
  }
  return v;
}

function __ftSplitValue(value, spec) {
  const out = {};
  if (!spec || typeof spec !== 'object') return out;
  const s = value == null ? '' : String(value);
  const parts = Array.isArray(spec.parts) ? spec.parts.filter(Boolean) : [];
  if (spec.mode === 'regex') {
    let m = null;
    try { m = s.match(new RegExp(spec.pattern || '', spec.flags || '')); } catch (_e) { m = null; }
    const groups = m && m.groups ? m.groups : null;
    if (groups && Object.keys(groups).length > 0) {
      for (const k of Object.keys(groups)) out[k] = groups[k] != null ? groups[k] : null;
    } else {
      for (let i = 0; i < parts.length; i++) out[parts[i]] = m && m[i + 1] != null ? m[i + 1] : null;
    }
  } else {
    const delim = spec.delimiter != null ? String(spec.delimiter) : ',';
    const pieces = delim === '' ? [s] : s.split(delim);
    for (let i = 0; i < parts.length; i++) {
      let piece = pieces[i] != null ? pieces[i] : null;
      if (piece != null && spec.trim !== false) piece = piece.trim();
      out[parts[i]] = piece;
    }
  }
  return out;
}

function __ftMaterializeRow(rawRow, fields) {
  const out = {};
  for (const name of Object.keys(fields || {})) {
    const spec = fields[name] && typeof fields[name] === 'object' ? fields[name] : {};
    let val = rawRow ? rawRow[name] : null;
    if (Array.isArray(spec.transforms) && spec.transforms.length) val = __ftCleanValue(val, spec.transforms);
    if (spec.split && typeof spec.split === 'object') {
      if (spec.split.keepOriginal) out[name] = val;
      const partsObj = __ftSplitValue(val, spec.split);
      for (const k of Object.keys(partsObj)) out[k] = partsObj[k];
    } else {
      out[name] = val;
    }
  }
  return out;
}

async function run() {
  const __results__ = {};

  const browser = await puppeteer.launch({
    // Honour CHROME_PATH when set (Linux servers / CI / containers); fall back
    // to the local Chrome install used during development.
    executablePath: process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-blink-features=AutomationControlled',
      '--window-size=1504,558',
    ],
  });

  let page = await browser.newPage();
  await applyStealthToPage(page);
  await page.setViewport({ width: 1504, height: 558, deviceScaleFactor: 1 });
  await page.setExtraHTTPHeaders({ 'Accept-Language': 'en-US,en;q=0.9' });

  // NOTE: The workflow's first step is the explicit NAVIGATE that pins
  // the start URL — we don't inject an extra page.goto here so the run
  // doesn't double-navigate when the user already has that step in the
  // workflow tree.

  try {
    // Navigate
    await page.goto("https://pwr.edu.pl/pracownicy/strefa-pracownika/wyszukiwarka-pracownikow", {
      waitUntil: "load",
      timeout: 30000,
    });
    // Click: #rejectAll
    {
      const _el = await waitForAny(page, [{ value: "#rejectAll", type: "css" }, { value: "div.modal-footer > button:nth-child(2)", type: "css" }, { value: "div.modal-footer > button:nth-of-type(2)", type: "css" }, { value: "button[type=\"button\"]:nth-of-type(2)", type: "css" }, { value: "button.btn.btn-secondary:nth-of-type(2)", type: "css" }, { value: ".btn.btn-secondary:nth-of-type(2)", type: "css" }], 10000);
      await _el.click();
    }
    {
      const _rep_total = 499;
      for (let i = 0; i < _rep_total; i++) {
          // Navigate
          await page.goto(`https://pwr.edu.pl/pracownicy/strefa-pracownika/wyszukiwarka-pracownikow?i_page=${i}`, {
            waitUntil: "load",
            timeout: 30000,
          });
          const extractlist_5jc9 = await (async () => {
            const _containers = await resolveElements(page, [{ value: "div.search-workers-result", type: "css" }]);
            return Promise.all(_containers.map(container =>
              page.evaluate((el, fields) => {
                const item = {};
                for (const [name, spec] of Object.entries(fields)) {
                  const sel = spec.selector || '';
                  // Empty selector means "use the container itself" (useful for
                  // attribute extraction off the row element).
                  const child = sel ? el.querySelector(sel) : el;
                  if (!child) { item[name] = null; continue; }
                  if (spec.kind === 'attr' && spec.attribute) {
                    item[name] = child.getAttribute(spec.attribute);
                  } else if (spec.kind === 'html') {
                    item[name] = (child.innerHTML || '').trim();
                  } else {
                    item[name] = (child.textContent || '').trim();
                  }
                }
                return item;
              }, container, {"name":{"selector":"table.white tbody tr:first-child th a","kind":"text","attribute":null},"profile_url":{"selector":"table.white tbody tr:first-child th a","kind":"attr","attribute":"href"},"email":{"selector":"table.white tbody tr:nth-child(3) td a[href^='mailto:']","kind":"attr","attribute":"href"},"unit":{"selector":"table.white tbody tr:nth-child(2) td div.fw-bold","kind":"text","attribute":null},"title":{"selector":"th > a","kind":"text","attribute":null}})
            )).then(_rows => _rows.map(_row => __ftMaterializeRow(_row, {"name":{"selector":"table.white tbody tr:first-child th a","kind":"text","attribute":null,"transforms":[{"op":"regex_extract","pattern":"^(?:(.*?)\\s+)?([A-ZĄĆĘŁŃÓŚŹŻ][A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż'-]+(?:\\s+[A-ZĄĆĘŁŃÓŚŹŻ][A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż'-]+)+)$","group":2}]},"profile_url":{"selector":"table.white tbody tr:first-child th a","kind":"attr","attribute":"href"},"email":{"selector":"table.white tbody tr:nth-child(3) td a[href^='mailto:']","kind":"attr","attribute":"href","transforms":[{"op":"slice","start":7}]},"unit":{"selector":"table.white tbody tr:nth-child(2) td div.fw-bold","kind":"text","attribute":null},"title":{"selector":"th > a","kind":"text","attribute":null,"transforms":[{"op":"regex_extract","pattern":"^(?:(.*?)\\s+)?([A-ZĄĆĘŁŃÓŚŹŻ][A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż'-]+(?:\\s+[A-ZĄĆĘŁŃÓŚŹŻ][A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż'-]+)+)$","group":1}]}})));
          })();
            if (!__results__["extracted_extractlist_5jc9"]) __results__["extracted_extractlist_5jc9"] = [];
            if (Array.isArray(extractlist_5jc9)) __results__["extracted_extractlist_5jc9"].push(...extractlist_5jc9);
            else if (extractlist_5jc9 !== null && extractlist_5jc9 !== undefined) __results__["extracted_extractlist_5jc9"].push(extractlist_5jc9);
      }
    }

  } catch (err) {
    console.error('❌ Workflow error:', err.message);
    process.exitCode = 1;
  } finally {
    try { await browser.close(); } catch (_) {}
  }

  // Output collected extraction results
  if (Object.keys(__results__).length > 0) {
    console.log('');
    for (const [key, value] of Object.entries(__results__)) {
      if (Array.isArray(value) && value.length > 0 && typeof value[0] === 'object') {
        // Tabular data from ForEach loop — print as table
        console.log('\n── ' + key + ' ──');
        const cols = Object.keys(value[0]);
        const widths = cols.map(c => Math.max(c.length, ...value.map(r => String(r[c] ?? '').length)));
        const hr = widths.map(w => '─'.repeat(w + 2)).join('┼');
        const header = cols.map((c, i) => ' ' + c.padEnd(widths[i]) + ' ').join('│');
        console.log(header);
        console.log(hr);
        value.forEach(row => {
          const line = cols.map((c, i) => ' ' + String(row[c] ?? '').padEnd(widths[i]) + ' ').join('│');
          console.log(line);
        });
      } else {
        console.log('\n── ' + key + ' ──');
        console.log(JSON.stringify(value, null, 2));
      }
    }
  }
  require('fs').writeFileSync('results.json', JSON.stringify(__results__, null, 2));
}

run().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
